#!/usr/bin/env bash
# configures a Nginx server so that /redirect_me redirects to another page
apt-get -y update
apt-get -y install nginx

echo '301 Moved Permanently' > /etc/nginx/html/index.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
