#!/usr/bin/env bash
# configures a new Ubuntu machine with a custom HTTP response header

sudo apt-get update -y
sudo apt-get install nginx -y

echo "location / {
    add_header X-Served-By $hostname;
}" | sudo tee /etc/nginx/conf.d/0-custom_http_response_header

sudo nginx -t

sudo systemctl reload nginx
