#!/usr/bin/env bash
# install and configure HAproxy on server using roundrobin algorithm

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y

sudo apt-get install haproxy=2.8.\* -y


echo "ENABLED=1" | sudo tee /etc/default/haproxy

cat <<EOF>"/etc/haproxy/haproxy.cfg"
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    user haproxy
    group haproxy

defaults
    log global
    mode http
    option httplog
    option dontlognull
    option redispatch
    retries 3
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http
    bind *:80
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web-01 242145-web-01:80 check
    server web-02 242145-web-02:80 check
EOF


sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
sudo systemctl enable haproxy
