#!/usr/bin/env bash
# install and configure HAproxy on server using roundrobin algorithm

sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y

sudo apt-get install haproxy=2.8.\* -y


echo "ENABLED=1" | sudo tee /etc/default/haproxy


echo "
frontend http
        bind *:80
	mode http
	default_backend web_backend

backend web_backend
	mode http
	balance roundrobin
	server web-01 35.227.45.0:80 check
	server web-02 35.237.153.115:80 check" >> /etc/haproxy/haproxy.cfg

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo systemctl restart haproxy
sudo systemctl enable haproxy
