#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.

FILENAME="/etc/passwd"

while IFS= read -r username _ userid _ homedir _
do
  echo "$username:$userid:$homedir"
done < $FILENAME
