#!/usr/bin/env bash
# This script is displaying "Best School" but "Hi" on its 9th iteration

count=1

while [[ $count -le 10 ]]; do
    if [[ $count -eq 9 ]]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$(( count + 1 ))
done
